import React, { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ShieldCheck, Search, FileImage, ExternalLink, CheckCircle2, Sparkles, UserCheck, Download, LoaderCircle, ListChecks, Settings2, BadgeCheck, Plus, Trash2, RotateCcw } from 'lucide-react';
import './styles.css';

type Status='found'|'not_found'|'unknown';
type TaskStatus='new'|'queued'|'done';
type Result={service:string;category:string;profile_url:string;delete_url:string;status:Status;http_status?:number;taskStatus:TaskStatus};
type Identity={id:string;type:'username'|'email'|'phone';value:string;verified:boolean};
type Tab='home'|'identities'|'results'|'files'|'settings';
const STORE='tracezero-v2-state';

function load(){try{return JSON.parse(localStorage.getItem(STORE)||'') as {identities:Identity[];results:Result[]}}catch{return {identities:[],results:[]}}}

function App(){
 const saved=load();
 const [tab,setTab]=useState<Tab>('home');
 const [identities,setIdentities]=useState<Identity[]>(saved.identities||[]);
 const [results,setResults]=useState<Result[]>(saved.results||[]);
 const [value,setValue]=useState('');
 const [type,setType]=useState<Identity['type']>('username');
 const [loading,setLoading]=useState(false);
 const [message,setMessage]=useState('Версия 2.0 загружена');
 const [cleaning,setCleaning]=useState(false);
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify({identities,results})),[identities,results]);
 const verifiedUsernames=identities.filter(i=>i.type==='username'&&i.verified);
 const found=results.filter(r=>r.status==='found');
 const queued=results.filter(r=>r.taskStatus==='queued');
 const done=results.filter(r=>r.taskStatus==='done');
 const score=useMemo(()=>results.length?Math.max(5,Math.min(95,20+found.length*7-done.length*5)):0,[results,found.length,done.length]);
 function addIdentity(){const clean=value.trim();if(!clean)return setMessage('Введите значение.');if(type==='username'&&!/^[A-Za-z0-9_.-]{2,40}$/.test(clean))return setMessage('Ник: латиница, цифры, точка, дефис или подчёркивание.');setIdentities(v=>[...v,{id:crypto.randomUUID(),type,value:clean,verified:false}]);setValue('');setMessage('Идентификатор добавлен. Подтвердите, что он принадлежит вам.');}
 function verify(id:string){setIdentities(v=>v.map(i=>i.id===id?{...i,verified:true}:i));setMessage('Подтверждено локально для MVP. В боевой версии будет код или OAuth.');}
 async function scanAll(){if(!verifiedUsernames.length){setTab('identities');return setMessage('Сначала добавьте и подтвердите хотя бы один свой ник.');}setLoading(true);setMessage('Проверяем открытые страницы…');try{const groups=await Promise.all(verifiedUsernames.map(async i=>{const r=await fetch(`/api/scan?username=${encodeURIComponent(i.value)}`);if(!r.ok)throw new Error();return await r.json()}));const merged=new Map<string,Result>();groups.flat().forEach((x:any)=>merged.set(`${x.service}:${x.profile_url}`,{...x,taskStatus:'new'}));setResults([...merged.values()]);setTab('results');setMessage('Проверка завершена. Откройте найденные страницы и подтвердите результат вручную.');}catch{setMessage('Сканирование не запустилось. Проверьте сборку Amvera и повторите.');}finally{setLoading(false)}}
 function queueAll(){setResults(v=>v.map(r=>r.status==='found'||r.status==='unknown'?{...r,taskStatus:'queued'}:r));setMessage('Все допустимые запросы добавлены в очередь.');}
 function setTask(key:string,s:TaskStatus){setResults(v=>v.map(r=>`${r.service}:${r.profile_url}`===key?{...r,taskStatus:s}:r));}
 async function cleanImage(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!f.type.startsWith('image/'))return setMessage('Поддерживаются изображения.');setCleaning(true);try{const b=await createImageBitmap(f);const c=document.createElement('canvas');c.width=b.width;c.height=b.height;c.getContext('2d')?.drawImage(b,0,0);const mime=f.type==='image/png'?'image/png':'image/jpeg';const blob=await new Promise<Blob|null>(r=>c.toBlob(r,mime,.94));if(!blob)throw new Error();const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=f.name.replace(/\.[^.]+$/,'')+'-clean.'+(mime==='image/png'?'png':'jpg');a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setMessage('Готово: EXIF и GPS удалены пересборкой изображения.');}catch{setMessage('Не удалось обработать файл.');}finally{setCleaning(false)}}
 return <div className="app"><header><div className="brand"><div className="logo"><ShieldCheck/></div><div><b>TraceZero <em>v2</em></b><span>Самоаудит цифрового следа</span></div></div><span className="safe">Только свои данные</span></header><main>{message&&<div className="notice">{message}</div>}
 {tab==='home'&&<><section className="hero glass"><div><span className="eyebrow"><Sparkles/> ЦИФРОВОЙ РИСК</span><h1>{results.length?score:'—'}<small>/100</small></h1><p>{results.length?`Проверено ${results.length} страниц, вероятно найдено ${found.length}.`:'Добавьте свои ники, подтвердите владение и запустите проверку.'}</p></div><div className="ring" style={{'--p':`${score}%`} as React.CSSProperties}><span>{results.length?score:'?'}</span></div></section><button className="primary" onClick={scanAll} disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Search/>}{loading?'Идёт проверка…':'Проверить мои профили'}</button><section className="stats"><article className="glass"><BadgeCheck/><b>{identities.filter(i=>i.verified).length}</b><span>подтверждено</span></article><article className="glass"><UserCheck/><b>{found.length}</b><span>найдено</span></article><article className="glass"><ListChecks/><b>{queued.length}</b><span>в очереди</span></article></section><section className="quick glass"><h2>Что умеет версия 2</h2><p>Поиск собственных публичных профилей, очередь официального удаления, массовое создание задач и локальная очистка фото.</p><button onClick={()=>setTab('identities')}>Добавить мои данные</button></section></>}
 {tab==='identities'&&<section><span className="eyebrow">МОИ ИДЕНТИФИКАТОРЫ</span><h2>Добавьте только свои данные</h2><div className="form glass"><select value={type} onChange={e=>setType(e.target.value as Identity['type'])}><option value="username">Ник</option><option value="email">Email</option><option value="phone">Телефон</option></select><input value={value} onChange={e=>setValue(e.target.value)} placeholder={type==='username'?'danil_28':type==='email'?'name@example.com':'+7…'}/><button onClick={addIdentity}><Plus/></button></div><div className="list glass">{identities.map(i=><div className="row" key={i.id}><div className="grow"><b>{i.value}</b><span>{i.type} · {i.verified?'подтверждено':'не подтверждено'}</span></div>{!i.verified&&<button onClick={()=>verify(i.id)}>Подтвердить</button>}<button className="iconOnly" onClick={()=>setIdentities(v=>v.filter(x=>x.id!==i.id))}><Trash2/></button></div>)}{!identities.length&&<div className="empty">Список пуст.</div>}</div><p className="hint">В MVP подтверждение локальное. SMS, email-коды и OAuth подключаются отдельными провайдерами.</p></section>}
 {tab==='results'&&<section><div className="headRow"><div><span className="eyebrow">РЕЗУЛЬТАТЫ</span><h2>Публичные страницы</h2></div><button className="mass" onClick={queueAll}>Удалить всё</button></div><p className="hint">Кнопка создаёт очередь официальных действий. Она не обходит пароль, CAPTCHA или двухфакторную защиту.</p><div className="list glass">{results.map(r=><ResultRow key={`${r.service}:${r.profile_url}`} r={r} setTask={setTask}/>)}{!results.length&&<div className="empty">Пока результатов нет.</div>}</div></section>}
 {tab==='files'&&<section><span className="eyebrow">ЛОКАЛЬНАЯ ОЧИСТКА</span><h2>Удалить метаданные</h2><div className="drop glass"><FileImage/><b>EXIF и GPS</b><p>Изображение обрабатывается в браузере и не загружается на сервер.</p><label>{cleaning?<><LoaderCircle className="spin"/> Обработка…</>:<><Download/> Выбрать фото</>}<input hidden type="file" accept="image/*" onChange={cleanImage}/></label></div></section>}
 {tab==='settings'&&<section><span className="eyebrow">НАСТРОЙКИ</span><h2>Данные приложения</h2><div className="quick glass"><p>Все введённые идентификаторы и результаты хранятся локально в браузере.</p><button className="danger" onClick={()=>{localStorage.removeItem(STORE);setIdentities([]);setResults([]);setMessage('Локальные данные удалены.')}}><RotateCcw/> Очистить всё</button></div></section>}
 </main><nav>{[['home','Обзор',ShieldCheck],['identities','Мои данные',BadgeCheck],['results','Результаты',Search],['files','Файлы',FileImage],['settings','Настройки',Settings2]].map(([id,label,Icon])=><button key={id as string} className={tab===id?'active':''} onClick={()=>setTab(id as Tab)}><Icon/><span>{label as string}</span></button>)}</nav></div>}
function ResultRow({r,setTask}:{r:Result;setTask:(k:string,s:TaskStatus)=>void}){const key=`${r.service}:${r.profile_url}`;const label=r.status==='found'?'Найден':r.status==='not_found'?'Не найден':'Проверить';return <div className="row"><div className={`dot ${r.status}`}/><div className="grow"><b>{r.service}</b><span>{r.category} · {label}</span></div><a href={r.profile_url} target="_blank" rel="noreferrer"><ExternalLink/></a>{r.status!=='not_found'&&(r.taskStatus==='done'?<CheckCircle2 className="ok"/>:<button onClick={()=>setTask(key,r.taskStatus==='queued'?'done':'queued')}>{r.taskStatus==='queued'?'Готово':'Удалить'}</button>)}{r.taskStatus==='queued'&&<a className="instruction" href={r.delete_url} target="_blank" rel="noreferrer">Инструкция</a>}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
